// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CheckList struct {
	ID       int    `json:"id"`
	Group    string `json:"Group"`
	Name     string `json:"Name"`
	Site     string `json:"Site"`
	Key      string `json:"Key"`
	URL      string `json:"URL"`
	IsRecord int    `json:"IsRecord"`
	OnLive   int    `json:"OnLive"`
}

type DeleteCheckListKey struct {
	ID int `json:"id"`
}

type EditCheckList struct {
	Group    string `json:"Group"`
	Name     string `json:"Name"`
	Site     string `json:"Site"`
	Key      string `json:"Key"`
	URL      string `json:"URL"`
	IsRecord int    `json:"IsRecord"`
	OnLive   int    `json:"OnLive"`
}

type Response struct {
	Code    int    `json:"Code"`
	Message string `json:"Message"`
}
