// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CheckList struct {
	ID       int    `json:"id"`
	Group    string `json:"Group"`
	Name     string `json:"Name"`
	Site     string `json:"Site"`
	URL      string `json:"URL"`
	IsRecord int    `json:"IsRecord"`
}

type NewCheckList struct {
	Group    string `json:"Group"`
	Name     string `json:"Name"`
	Site     string `json:"Site"`
	URL      string `json:"URL"`
	IsRecord int    `json:"IsRecord"`
}
